[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.18"

remappings = [
  "chainlink=lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/interfaces",
  "mocks=test/mocks",
  "forge-std=lib/forge-std/src"
]
